list-page-size: 5
messages: # Can be used to add translation
    info: # To turn off certain messages leave the field empty (not empty quotes!)
    error:
        no-permission: Not enough permissions to call this command!
        invalid-command: Invalid command!
        synced-clock-set: Unable to change synced clock settings!
    help: # Not intended to be edited (unless adding translation)
        header: §7-------- §6[§aBlockOClock§6] §7--------------------------
        help: §a/boc §6help §a[command] §r- Show help for given command, for available commands otherwise
        reload: §a/boc §6reload §r- Reload config
