default-font-size: 3
list-page-size: 5
messages: # Can be used to add translation
    info: # To turn off certain messages leave the field empty (not empty quotes!)
        overworld: Overworld
        nether: Nether
        end: End
        custom: Custom # for "custom" dimension (probably useless)
        clock-created: Created {clock}
        clock-deleted: Deleted {clock}
        clock-started: Started {clock}
        clock-stopped: Stopped {clock}
        clock-set-time: Set time {time} on {clock}
        clock-set-direction: Direction set {direction} on {clock}
    error:
        no-permission: Not enough permissions to call this command!
        invalid-command: Invalid command!
        nonexistent-clock: Clock with this ID does not exist!
        synced-clock-set: Unable to change synced clock settings!
    help: # Not intended to be edited (unless adding translation)
        header: §7-------- §6[§aBlockOClock§6] §7--------------------------
        help: §a/boc §6help §a[command]§r - Show help for given command, for available commands otherwise
        list: §a/boc §6list §a<nearest\|ordered> [page=1]
        create: §a/boc §6create §a<*settings>
        delete: §a/boc §6delete §a<id>
        start: §a/boc §6start §a<id>
        stop: §a/boc §6stop §a<id>
        set-time: §a/boc §6set time §a<id> <hh:mm:ss.tt>
        set-direction: §a/boc §6set direction §a<id> <up\|down>
        reload: §a/boc §6reload§r - Reload config
