name: BlockOClock
version: '${project.version}'
api-version: '${mcApi.version}'
main: me.kruase.block_o_clock.BlockOClock
authors: [ KruASe ]

description: Allows to create clocks from blocks in the world

commands:
    blockoclock:
        description: Main BlockOClock plugin command
        permission: blockoclock.help
        usage: |-
            §7Run §6/help <command> [n] §7to get page n of help
            §a/<command> §6help §a[command] §r- Show help for given command, for available commands otherwise
            §a/<command> §6reload §r- Reload config
            §cWARNING: §eCommands listed here might be unavailable for you, to get help for available commands run §a/<command> help
        aliases:
            - boc

permissions:
    blockoclock.help:
        description: Allows to use §a/boc §6help §r(lists only available commands)
        default: true
    blockoclock.reload:
        description: Allows to use §a/boc §6reload
        default: op
    blockoclock.admin:
        description: Refers to §blockoclock.reload §rby default
        default: op
        children:
            blockoclock.reload: true
