name: BlockOClock
version: '${project.version}'
api-version: '${mcApi.version}'
main: me.kruase.block_o_clock.BlockOClock
authors: [ KruASe ]

description: Allows to create clocks from blocks in the world

commands:
    blockoclock:
        description: Main BlockOClock plugin command
        permission: blockoclock.help
        usage: |-
            §7Run §6/help <command> [n] §7to get page n of help
            §a/<command> §6help §a[command]§r - Show help for given command, for available commands otherwise
            §a/<command> §6list §a<nearest|ordered> [page=1]§r - List all clocks in the world (with IDs) with given sorting
            §a/<command> §6create §a<*settings>§r - Create new clock in the world (and print its ID)
            §a/<command> §6delete §a<id>§r - Delete the clock (and fill it with air)
            §a/<command> §6start §a<id>§r - Start stopped clock
            §a/<command> §6stop §a<id>§r - Stop the clock (won't update until calling §a/boc §6start§r on it)
            §a/<command> §6set time §a<id> <HH:mm:ss.tt>§r - Set given time on §enon-synced§r clock (if the time unit is not displayed its value can be just zeros)
            §a/<command> §6set direction §a<id> <up|down>§r - Set given direction on §enon-synced§r clock
            §a/<command> §6reload§r - Reload config
            §cWARNING: §eCommands listed here might be unavailable for you, to get help for available commands run §a/<command> help
        aliases:
            - boc

permissions:
    blockoclock.help:
        description: Allows to use §a/boc §6help§r (lists only available commands)
        default: true
    blockoclock.list:
        description: Allows to use §a/boc §6list
        default: op
    blockoclock.create:
        description: Allows to use §a/boc §6create
        default: op
    blockoclock.delete:
        description: Allows to use §a/boc §6delete
        default: op
    blockoclock.start:
        description: Allows to use §a/boc §6start
        default: op
    blockoclock.stop:
        description: Allows to use §a/boc §6stop
        default: op
    blockoclock.set:
        description: Allows to use §a/boc §6set
        default: op
    blockoclock.reload:
        description: Allows to use §a/boc §6reload
        default: op
    blockoclock.use:
        description:
            Refers to §2blockoclock.list§r, §2blockoclock.start§r, §2blockoclock.stop§r and §2blockoclock.set§r by default
        default: op
        children:
            blockoclock.list: true
            blockoclock.start: true
            blockoclock.stop: true
            blockoclock.set: true
    blockoclock.manage:
        description: Refers to §2blockoclock.create§r, §2blockoclock.delete§r and §2blockoclock.use§r by default
        default: op
        children:
            blockoclock.create: true
            blockoclock.delete: true
            blockoclock.use: true
    blockoclock.admin:
        description: Refers to §2blockoclock.reload§r and §2blockoclock.manage§r by default
        default: op
        children:
            blockoclock.reload: true
            blockoclock.manage: true
